### ISSUE TITLE
Update documentation for Version 002

### ISSUE THREAD

**Issue by vyuh** [standardfile/standardfile.github.io#10]
- Version 002 no longer has `pw_auth` field in `user` model as I infer from [this](https://github.com/standardfile/ruby-server/blob/ad2215a4df787cb7b7a2fcdfd64531e15cfb5595/db/migrate/20170808194325_remove_pw_auth.rb#L3). All mentions of it in documentation should be appropriately removed/updated. Anyone willing to work on this may start [here](https://github.com/standardfile/standardfile.github.io/blame/2408bff600ef73808410af653d10cba378260a85/doc/spec.md#L56)
- The order of components shown in definitions involving [`string_to_auth`](https://github.com/standardfile/standardfile.github.io/blame/master/doc/spec.md#L389) is incorrect at many places. `IV, uuid` needs to be replaced with `uuid, IV`. This should be the correct order as [the Standard Notes web client](https://github.com/standardnotes/web/blob/1ad0bf73d8e995b7588854f1b1e4e4a02303a42f/app/assets/javascripts/app/services/helpers/encryptionHelper.js#L13) seems to use it.

(It'll help if you refer to lines of code linked above.)

**Comment by mobitar** [comment]
Thanks for catching this, I've deployed the fixes.
